### ISSUE TITLE
Non-deterministic pipeline runs

### ISSUE THREAD

**Issue by RFMVasconcelos** [canonical/kfp-operators#15] opened 2021-06-14 13:30 UTC
Pipelline runs appear to be stochastic, e.g. I installed Kubeflow and ran the pre-built XGBoost example. The pipeline broke the first 2 times I ran it, but worked the third time.. 

![Screenshot from 2021-06-14 14-28-05](https://user-images.githubusercontent.com/27001378/121899952-ca323b00-cd1c-11eb-82cc-ae4053415482.png)

Thought this might be interesting to document / discuss.

**Comment by knkski** [comment] 2021-06-14 14:10
This is actually a duplicate of #8. The bug there and here is that the Argo sidecar doesn't work well with short-lived workflow steps, so the behavior you're seeing here is that if the step takes just long enough, Argo works fine, but most of the time it won't work on short-lived workflow steps. Closing since this should be fixed on our end by #11, which just removes the broken pipeline samples. It would be good to document what steps people would need to do to run them, but that's a separate issue.

**Closed by knkski** 2021-06-14 14:10 UTC
