### ISSUE TITLE
bundle integration tests failing

### ISSUE THREAD

**Issue by NohaIhab** [canonical/kfp-operators#252] opened 2023-07-14 09:29 UTC
logs in https://github.com/canonical/kfp-operators/actions/runs/5546710975/jobs/10127367018?pr=234
needs investigation

**Comment by DnPlas** [comment] 2023-07-14 12:51
Hi @NohaIhab, this is a duplicate of #250, which should be fixed by #254. Closing it in favour of that other issue.

**Closed by DnPlas** 2023-07-14 12:51 UTC
