### ISSUE TITLE
Recurring runs are no more running after upgrading to 1.8

### ISSUE THREAD

**Issue by eleblebici** [canonical/kfp-operators#480] opened 2024-05-28 07:20 UTC
### Bug Description

I had Charmed Kubeflow 1.7 and upgraded it as explained [here](https://charmed-kubeflow.io/docs/upgrade-17-18). Before upgrading I was able to create recurring run and there was no problem with that. As explained in the documentation, I disabled the recurring run before the upgrade and after successfully upgrading the CK to 1.8, I enabled it back. But recurring runs are no more running.

### To Reproduce

1- juju deploy kubeflow --channel=1.7/stable
2- Create the sample pipeline as explained [here](https://charmed-kubeflow.io/docs/explore-kubeflow#heading--kubeflow-pipeline)
3- Create the experiment and recurring run which is using this pipeline.
4- Upgrade the kubeflow to 1.8 as explained [here](https://charmed-kubeflow.io/docs/upgrade-17-18). Disable the recurring run before the upgrade 
5- After the upgrade, enable the recurring run again. 
6- Recurring runs are not running any more.

### Environment

Charmed Kubeflow 1.8
Kubernetes cluster 1.24
Juju 3.4.2

### Relevant Log Output

```shell
I am not sure what logs can be useful. Please let me know if you need any logs, outputs, etc.
```

**Comment by DnPlas** [comment] 2024-06-19 15:55
Closing as a duplicate of https://github.com/canonical/kfp-operators/issues/517

**Closed by DnPlas** 2024-06-19 15:55 UTC
Labels: bug
